### ISSUE TITLE
Re;Birth 1 support

### ISSUE THREAD

**Issue by DefiantCatgirl** [tlaik/neptastic#1]
Is it possible to also support Re;Birth 1? Hyperresolution has some graphical glitches when displaying animated 2D content, especially on certain chips (cough, Intel, cough), so it's not always usable.

**Comment by tlaik** [comment]
Added Re;Birth1 support in [v1.1.0](https://github.com/tlaik/neptastic/releases/tag/v1.1.0)

It's hard to pin down exact problem with that chip without debugging drivers and/or at least having direct access to one. I added a Safe mode switch to the .ini file, which you can try using to avoid CG glitches. It'll most likely also disable equipment preview.
