### ISSUE TITLE
The resolution scaling breaks sometimes and renders at a much lower resolution than it should.

### ISSUE THREAD

**Issue by HoundedoutBanger** [tlaik/neptastic#11]
Sometimes when launching Rebirth 1 with this mod installed the game's rendering resolution will be much lower than it should be and make the game all pixelated/unplayable. It doesn't happen every time I launch the game but once it does it will happen every time after that until I turn my pc off.
I haven't had the chance to play the other games so I don't know if it happens with them yet.

This is an image to show what I mean.
That's on a 1440p monitor with resolution scaling at 2.0.
![20211122104721_1](https://user-images.githubusercontent.com/95057512/143509206-fda141e3-9d30-46e0-8c8b-1ad8af34bdd7.jpg)

**Comment by tlaik** [comment]
Random resolution change without touching .ini file, and it sticks around until PC restart? Sounds like something fishy with the drivers. What's your GPU?

**Comment by tlaik** [comment]
Random resolution change without touching .ini file, and it sticks around until PC restart? Sounds like something fishy with the drivers. What's your GPU?

**Comment by HoundedoutBanger** [comment]
> Random resolution change without touching .ini file, and it sticks around until PC restart? Sounds like something fishy with the drivers. What's your GPU?

It's an Nvidia 3060ti. I believe I'm on the latest drivers.

**Comment by tlaik** [comment]
Alright, try to get this bug to happen again. Once the game starts launching with wrong resolution, go to **nep.ini** and set "Log level" to 4. Launch the game and exit once you see the pixelated menu like in your screenshot.
You will have a huge, detailed log file in game directory - upload it somewhere, like [pastebin.com](https://pastebin.com) and I'll see if there are any hints as to what's happening.

**Comment by HoundedoutBanger** [comment]
> Alright, try to get this bug to happen again. Once the game starts launching with wrong resolution, go to **nep.ini** and set "Log level" to 4. Launch the game and exit once you see the pixelated menu like in your screenshot. You will have a huge, detailed log file in game directory - upload it somewhere, like [pastebin.com](https://pastebin.com) and I'll see if there are any hints as to what's happening.

So I tried to get it to happen again for a while today but it wasn't happening for whatever reason.
I'm not going to have much chance in the next couple of days to play but when/if it happens again I'll upload that log file for you.

**Comment by Wiltedmallard49** [comment]
I know this is an old issue, but i have been having the same problem, here is a link to the log: https://files.catbox.moe/ws6uxa.log

**Comment by tlaik** [comment]
'Tis **very** interesting. Thanks for the log. The game window is initially created with this bizarre size of 480x38, despite resolution in settings looking to be 1280x720.
After that, the mod just multiplies this initial size by 2 (not expecting anything weird) and your game ends up rendering at 960x76.
Having no idea why in the bloody 'elle game window would behave like that, I shall simply add an option to directly set the desired render resolution, as an alternative to using a multiplier.

**Comment by tlaik** [comment]
> I know this is an old issue, but i have been having the same problem, here is a link to the log: https://files.catbox.moe/ws6uxa.log

'Tis very interesting. Thanks for the log. The game window is initially created with this bizarre size of 480x38, despite resolution in settings looking to be 1280x720.
After that, the mod just multiplies this initial size by 2 (not expecting anything weird) and your game ends up rendering at 960x76.
> [V]: glViewport enter | id: 0, x: 0, y: 0, width: 1280, height: 720
[V]: Getting window
[I]: Window @ 0x000404d4 - client size 480 x 38
[V]: Computing settings
[I]: Resolution: 960 x 76, shadow size: 4096

Having no idea why in the bloody 'elle game window would behave like that, I shall simply add an option to directly set the desired render resolution, as an alternative to using a multiplier.

**Comment by tlaik** [comment]
Observe and experience: The brand new [version 1.1.7](https://github.com/tlaik/neptastic/releases/download/v1.1.7/Neptastic_Mod_v1.1.7.zip) with specific resolution settings.
Render width and height are left at 0 by default, since the multiplier works fine for most people. But in your case you can set those parameters to whatever you truly desire - a 2x scaling would be 3840x2160 for 1080p or 5120x2880 for 1440p. Go try it out.

**Comment by Wiltedmallard49** [comment]
Thanks, i'll use the new version and report if it happens again.
