### ISSUE TITLE
Rebirth 3 crashes randomly with neptastc installed.

### ISSUE THREAD

**Issue by mer2329** [tlaik/neptastic#13]
Rebirth 3 crashes randomly with neptastc installed. and its truly random, but seems to do it more when stating battle, and loading screens, so it might be transitions. 
the duration between crashes is pretty random, sometimes its less then 30 minutes, sometimes its a few hours, and sometimes it docent crash at all. 

attached is all my crash reports i have
[Hyperdimension Neptunia Re;Birth3.zip](https://github.com/tlaik/neptastic/files/8710726/Hyperdimension.Neptunia.Re.Birth3.zip)
SHA1: a70f5b95c41ba356ed9df523d9fead28909344b1

**Comment by mer2329** [comment]
i should add the most recent crash report had the large memory patch applied, and a few of them might have had special K injected (cant remember about special k though) and the crash goes away if i play rebirth 3 vanilla. 
no crashes on the first 2 games.

**Comment by mer2329** [comment]
oh in case my setup isnt in the dumps. 
CPU: ryzen 5 3600
GPU: GTX 1650, 4GB GDDR6
RAM: 32GB 2400 DDR4
game is installed to my C drive on a NVME (this NVME uses system ram as a cache)

if you need any more info please let me know, and ill gather it if i can.

**Comment by tlaik** [comment]
Try to disable FPS unlock first. Neps run on the Phyre Engine - same one used by Dark Souls 1 - and it's notorious for having random glitches when not running at intended framerate (check out 60 fps issues with DS1). For some people it still works fine, for others, not so much.

**Comment by tlaik** [comment]
See if reducing shadow size (down to 2.0 or even 1.0) helps, and then perhaps combining it with render resolution at 1.0 if crashes persist. You can also try disabling mod functionality one by one at the bottom of nep.ini file - in this case, also try to disable shadow control first, then resolution, and after that memory & texture optimizations.

**Comment by mer2329** [comment]
ill try thanks for gettign back to me. ill reply if it helps

**Comment by mer2329** [comment]
also there is no `Shadow size` so ima assume you meant `Shadow resolution`, also `render resolution` isnt an option, ima assume you meant `Resolution scaling`

**Comment by mer2329** [comment]
removed, cause i just realized i forgot to reenable the mod during testing.......

**Comment by tlaik** [comment]
So, it's the same result even with shadow and render resolution turned all the way down, and memory/texture optimization disabled?
If that's the case, I've honestly no idea what might be happening, sorry. I had some crashes during testing, and it was due to the settings mentioned above - running into the memory limits of a 32-bit process with overly large textures. When memory isn't the issue, no one seemed to have such problems until now...

**Comment by mer2329** [comment]
sorry i didnt test. i forgot to reenable the mod when i tried to test. then i 100%ed the steam achievements.

**Comment by mer2329** [comment]
this was more so giving you the crash reports in case those could help you improve it.
