### ISSUE TITLE
Game white screen on start up

### ISSUE THREAD

**Issue by TobySealz** [tlaik/neptastic#14]
https://pastebin.com/MAwT1Vdg

The game start up and after the logo sound effect it just stuck there and I had to force it off, tried removing the mod and worked afterward.

i7-10750H RTX20608gb with 16G ram, game is installed on a external drive since I'm using a laptop.

I'm also using a external 2k monitor as my main display.

sorry for the reopen this is my first time using github and im dumb

**Comment by tlaik** [comment]
It's alright. What's the exact name of your game window, and where did you get the game - is it on Steam, GoG, or some other place?

**Comment by TobySealz** [comment]
Sorry for the late reply, time zone could make this really painful to go through, I'm playing on steam's official version with traditional chinese.
![Screenshot_2](https://user-images.githubusercontent.com/96244332/171336572-d210a750-2c51-46be-af19-1b0c082cde6f.png)

**Comment by tlaik** [comment]
Alright, try this version - I changed Nep window detection method from window title to window class, which localizers hopefully did not touch.
[opengl32.zip](https://github.com/tlaik/neptastic/files/8813402/opengl32.zip)

**Comment by TobySealz** [comment]
Thank you, that worked!
The rest of the mod is working perfectly, but it seems that the resolution setting is not effecting anything as it still start up as 1088p and cant go up in setting, or am I mistaking the "Exact rendering width & height" in config? (I set it at 2560 1440)

**Comment by tlaik** [comment]
You don't need to change "Exact rendering width & height" from 0, unless "Resolution scaling" isn't working for you. Set those back to zero and see if upscaling works after that.

**Comment by TobySealz** [comment]
Sorry, I've tried setting exact rendering to 0 and resolution scaling to 1.0/2.0 but both doesnt render the game at 2k

**Comment by tlaik** [comment]
Alright, can you give me your current game log?

**Comment by TobySealz** [comment]
[nep.log](https://github.com/tlaik/neptastic/files/8831908/nep.log)

here!

**Comment by tlaik** [comment]
It seems like the rendering resolution is indeed set to twice your window size. What makes you feel like it wasn't changed?

Or do you want to resize the game window (in particular, make it larger than 1920x1080)? If so, that's not what resolution scaling is about - it's there to make game draw picture at higher resolution and scale it down to window size, which produces nice, clean anti-aliasing effect.

**Comment by TobySealz** [comment]
Ah that's my bad then, guess I'm just too dumb to realize that, we're all clear here then, Thanks for the help!

**Comment by tlaik** [comment]
Nice to hear, gonna close this issue now.
