### ISSUE TITLE
Shadow resolution option doesn't work on Rebirth2 GOG version

### ISSUE THREAD

**Issue by Drakensangs** [tlaik/neptastic#15]
The shadow resolution works perfectly fine on Rebirth 1 and 3 GOG versions, but for some reason it doesn't really do anything on Rebirth 2. 
Here's a screenshot of the game running with shadow res set to 8:

![Untitled](https://github.com/tlaik/neptastic/assets/51763452/6870c7e7-f164-44ff-b5d1-85b5b838de7b)

Tried disabling the mod's other functionalities but that didn't help at all.

Verbose log: 
[nep.log](https://github.com/tlaik/neptastic/files/12365592/nep.log)

**Comment by tlaik** [comment]
Can you upload the .exe file of your Rebirth 2? Game's shaders are stored inside main executables, and there might be some difference between Steam and GOG versions.

**Comment by Drakensangs** [comment]
Here's the executable:
[NeptuniaReBirth2 exe.zip](https://github.com/tlaik/neptastic/files/12383644/NeptuniaReBirth2.exe.zip)

**Comment by tlaik** [comment]
Thanks. Things are weird. I checked the shaders, and everything that's being replaced by the mod is the same in both versions. And when running the game with this exe, shadow control works fine for me. Your nep.log also doesn't contain any errors... are you sure you didn't have any other mods running, like ReShade?
![rb2_gog_1](https://github.com/tlaik/neptastic/assets/15186019/1c1df4a0-8d68-476c-9c4a-dcd522db40bb)

**Comment by Drakensangs** [comment]
Don't have any mods or anything else running alongside the game. I even went ahead and reinstalled it just to be sure and the shadow resolution issue still persists.

**Comment by tlaik** [comment]
I also downloaded the full GOG version just now and tried running it with the mod - again, everything works fine.
What's also interesting is the GOG exe version - in the window title it says "REV: 85", whereas Steam version and the exe you sent are "REV: 84". Can you try and update your copy of the game?

Here's just the exe file, maybe replacing it alone will help: [NeptuniaReBirth2_GOG_REV85.zip](https://github.com/tlaik/neptastic/files/12387671/NeptuniaReBirth2_GOG_REV85.zip)

**Comment by Drakensangs** [comment]
Trying to use that executable just results in a crash at startup.

I'm curious about the folder structure of the version you downloaded. Went through gogdb.org and there are two versions of the game listed there. One from 2017 and one from 2019. The 2017 version is structured thusly: https://www.gogdb.org/manifest/519a37992bb4c8dd11b0d22e412b9062
While the 2019 version (the one that I have installed) is as follows:
https://www.gogdb.org/manifest/e39c264b0f5aa0fc7257abdd8943999b

**Comment by Kamletue** [comment]
Commenting on this to say that this is still an issue on the latest GOG revision (labeled "gog-3") and game "REV:84"; shadow resolution control doesn't work.
