### ISSUE TITLE
ReShade breaks shadow control when used with Neptastic Mod

### ISSUE THREAD

**Issue by Drakensangs** [tlaik/neptastic#16]
I'm trying to use ReShade with the Neptastic Mod to inject some FXAA since it's infinitely better than the game's default FXAA, however ReShade completely kills all the shadows in the game. Here's a screenshot of Neptastic Mod and ReShade working together:

![Untitled1](https://github.com/tlaik/neptastic/assets/51763452/73057c82-b844-4f00-8a97-2cb92004977f)

Disabling shadow control in nep.ini restores the game's low res vanilla shadows.

Verbose log:
[nep.log](https://github.com/tlaik/neptastic/files/12365774/nep.log)

ReShade log (if it helps at all):
[ReShade.log](https://github.com/tlaik/neptastic/files/12365788/ReShade.log)

**Comment by tlaik** [comment]
Sorry, but I've no idea what this ReShade mod/shader is doing and in what order, so I can't comment on it.
You can find sources for shader replacements - including the one used for shadows - in this file and try to integrate them with whatever you're injecting:
https://github.com/tlaik/neptastic/blob/main/src/nep_shaders.h

**Comment by Drakensangs** [comment]
After further messing around with the shadow options and ReShade, it seems that ReShade doesn't kill the shadows, they're still working, but the higher the shadow resolution goes, the more offset they become, so at 4.0 and 8.0 the shadows are still rendering, but they're all most likely completely off the map. Setting the shadow resolution to 1.0 works, but at that point it's pretty much the same as using the game's vanilla shadows. Anything over 1.0 offsets them.

Here's an example with the shadows set to 1.1:

![NeptuniaReBirth1 2023-08-24 19-13-56](https://github.com/tlaik/neptastic/assets/51763452/97e4b771-f75f-4bf8-afba-37c36ae42fc3)

Would it be possible at all to add a shadow offset option to the mod to deal with this?
