### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Triticum0** [tlaik/neptastic#17]
I was wondering if hyperdimension neptunia Re;Birth2 ever had the teleport bug which appeared in Hyperdimension Neptunia Re;Birth3 when going above 60fps.

As testing Hyperdimension neptunia mk2 on rpcs3 I ran into that issue due to higher frame rates on the emulator and I'm sure it is an engine bug or the emulator.

The same thing also happens in hyperdimension neptunia victory on rpcs3 which is known to have the bug on pc from information gathered from Steam forums and Reddit.

I know you added Frame unlocked for Re;Birth1 and 2 so I wanted to know if you encountered any issues with frame rate being tied to movement speed/teleport bug in the rest of the series when making the mod or if the engine bug only affected Re;Birth3. Sorry for posting this on GitHub, there wasn't much info online using google.

Thank in advance

**Comment by tlaik** [comment]
Re;Birth 1-3 all use very similar engine versions, and with FPS unlocked all had this bug show up for few people here and there. Running out of bounds, teleporting, that kinda stuff. Seems to work fine most of the time, though.
