### ISSUE TITLE
[Linux] Shadow Resolution below 2.0 breaks portraits on Re;birth2

### ISSUE THREAD

**Issue by Vthyarilops** [tlaik/neptastic#18]
I don't believe this is intended behavior but if Shadow Resolution is set to 1.0 portraits completely disappear, if set above 1.0 but below 2.0 they partially appear, doesn't happen in Re;birth1 with the same configuration file, unfortunately I don't have a Windows computer to test if this behavior occurs.

Shadow resolution at 1.0:
![shadow10](https://github.com/tlaik/neptastic/assets/32111041/baa00246-413f-46a3-bd85-6f6f719a1d95)

Shadow resolution 1.75:
![shadow175](https://github.com/tlaik/neptastic/assets/32111041/0940b5a8-e4d6-41b5-b12c-6c11f8313fc4)

Log file 
[nep.log](https://github.com/tlaik/neptastic/files/14130150/nep.log)

**Comment by tlaik** [comment]
I don't see obvious issues with texture/viewport sizes in the log... try disabling some functionality at the bottom of the .ini file. It is indeed not an intended look.

**Comment by Vthyarilops** [comment]
If I disable shadow control it fixes it (or set the resolution to 2.0 or above), I tried disabling all the other options to no avail, it's not really a big deal but if it is reproducible it might be a good idea to add a note to the readme. I can test further if needed but this happens on Steam Deck and my desktop, both are AMD Mesa unsure if it's relevant

**Comment by tlaik** [comment]
Very interesting. I tested it on Linux & Windows - but with an Nvidia GPU - and didn't see this bug.
Thanks for the heads-up, I'll add this warning later. I don't have anything with AMD GPU, so can't really guess what's going wrong. Looks like a difference in driver behaviour.
