### ISSUE TITLE
Error for the mod 

### ISSUE THREAD

**Issue by PJRyu** [tlaik/neptastic#19]
When I start the game with the mod installed, the game freezes and doesn't work anymore
Log:
[I]: Commence the Nep log for RB3
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[E]: GL error: 0x0506
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024
[I]: Resolution: 0 x 0, shadow size: 1024

**Comment by tlaik** [comment]
Can you attach your nep.ini file as well?

**Comment by PJRyu** [comment]
I am so sorry for this late response I was not able to respond yesterday, Github does not allow the ini file type so I will just Post all of my settings here, thank you for your help by the way.


// 1.0 = Render at window/screen size. Higher numbers produce smoother image, but values above 2.0 are not recommended
Resolution scaling: 2.0

// Exact rendering width & height - will be used instead of scaling multiplier if width & height are non-zero
Render width: 0
Render height: 0

// Only for RB1 & RB2 || Yes = Unlimited FPS, No = Default 60 FPS cap. Disable if experiencing weird teleporting in-game (thanks PhyreEngine)
FPS Unlock: Yes

// 1 = No VSync, 2 = VSync, 3 = Adaptive VSync (Recommended)
VSync type: 3

// Yes = Simple gray outlines, No = Default textured outlines
Simple outlines: No
Outlines intensity: 0.2

// 1.0 = 1024x1024, 2.0 = 2048x2048, etc.
Shadow resolution: 1.0
Shadow blur: 1.0

// Bloom intensity has the most effect, reasonable values are up to ~1.2
Bloom intensity: 0.6
Bloom contrast: 2.0
Bloom softness: 10.0
Bloom samples: 5

// Avoids problems (such as broken Live2D CG) with certain drivers by disabling some functionality
Safe mode: No

// 0: Off, 1: Errors, 2: Warnings, 3: Information, 4: Verbose
Log level: 3

// Mod functionality switches
Enable resolution control: Yes
Enable new FXAA and bloom: Yes
Enable outline control: Yes
Enable shadow control: Yes
Enable anisotropy: Yes
Enable VSync control: Yes
Enable texture compression: Yes
Enable memory optimization: Yes

**Comment by tlaik** [comment]
The config file seems fine.
Are you using Steam or GoG version, and are they up-to-date?
What's the exact title of your game window? For example, here's the one I'm working with:
![image](https://github.com/user-attachments/assets/2d934f89-f566-400d-bebf-f5f7a8c4ec0b)

**Comment by PJRyu** [comment]
I am using the steam version and I've made sure they're up to date.
Here's the title of my game window. Would the game be causing problem because of my language options?
![image](https://github.com/user-attachments/assets/00bc4d5a-5504-4acf-a7cc-f5375093ca28)

**Comment by tlaik** [comment]
Language is definitely the issue here - this mod is looking for the game window by its English title.
Try using the .dll attached below, I updated it to use a different search method.

[neptastic_117_wnd_class.zip](https://github.com/user-attachments/files/16346346/neptastic_117_wnd_class.zip)

**Comment by PJRyu** [comment]
Alright thank you so much!

**Comment by tlaik** [comment]
Does the fix work for you? If so, I'll update the downloadable version.

**Comment by PJRyu** [comment]
Sorry for the late reply again and yes it definitely worked thanks for your help.
