### ISSUE TITLE
Re;Birth3 pictures glitch

### ISSUE THREAD

**Issue by Jeropeesee-Bashan** [tlaik/neptastic#2]
Tried playing Re;Birth3 with the mod and found a glitch related to the in-game pictures like those from Museum or backgrounds. Some of them has no color and "squeezed" as in the example.
![NeptuniaReBirth3_PRLkdqKJe8](https://user-images.githubusercontent.com/78712563/126853294-30e0b6e7-fb9a-4d61-b999-af6a63dbe885.jpg)

**Comment by tlaik** [comment]
Fixed in [v1.1.0](https://github.com/tlaik/neptastic/releases/tag/v1.1.0)

**Comment by tlaik** [comment]
Fixed in [v1.1.0](https://github.com/tlaik/neptastic/releases/tag/v1.1.0)
