### ISSUE TITLE
A problem in ReBirth1

### ISSUE THREAD

**Issue by CynAlde** [tlaik/neptastic#20]
![20241028140938_1](https://github.com/user-attachments/assets/97621583-bada-4bed-b379-a22c6fab8796)
Some of the live 2d that Default graphics would appear in the game will happened a black screen, such as a very beginning sense in rebirth1 . It will go black after using neptastic.

**Comment by tlaik** [comment]
Try changing "Enable texture compression" in the nep.ini to "No". It caused this problem for some people.
