### ISSUE TITLE
A question about the sprites

### ISSUE THREAD

**Issue by D3fau4** [tlaik/neptastic#4]
Hello and sorry for asking you about this, I know this is not related about your mod but maybe you can help me or guide me with this. I want make a mod for nep Re;2 and I would like to resize the sprites to a higher resolution so they don't look pixelated, i was searching in ida and i think i only found the function what sets the window size.
![unknown-51.png](https://user-images.githubusercontent.com/19638408/127368317-29e2186a-6b58-4504-b670-41c619897e04.png)
![unknown-63.png](https://user-images.githubusercontent.com/19638408/127368345-f1b14276-fa3c-46d3-861d-444d9eafd126.png)

so i wanted to ask you if you know anything related about this and thanks for this mod its really cool. If you want talk in another place i can give you my Twitter, discord or my telegram if you want.

**Comment by tlaik** [comment]
I'm honestly not sure what you're trying to achieve and what you mean by "sprites" - is it backgrounds, Live2D elements, in-game sprites in 3D world? At the end of the day, all of those are raster images and have a finite resolution. They might appear sharper as you increase the overall game resolution, but at some point the image itself won't be large enough to increase picture quality any further.
If I'm misunderstanding something, you can try explaining it in Discord, mine is `video0#0001`

**Comment by D3fau4** [comment]
Hey! are you still available on discord? I told you some things a few weeks ago.
