### ISSUE TITLE
3D graphics go plain black on victory screen

### ISSUE THREAD

**Issue by Oscarg73** [tlaik/neptastic#5]
Hi! First, many thanks for this amazing mod.

I have the trilogy on Steam with the last updates and I'm using the last version of your mod (1.1.4). The problem is that all the 3D graphics go plain black the exact moment the victory animation ends. The 2D graphics as the results/level up screen keep showing without problem. The game neither crash.

**R;B1:**
![20210729090526_1](https://user-images.githubusercontent.com/25150787/127451337-73d9058a-756b-4e3b-9296-57281eceeb0b.jpg)
![20210729090527_1](https://user-images.githubusercontent.com/25150787/127451391-0041b4b4-8ffc-4e46-8030-8f3f096ad8d6.jpg)

**R;B2**
![20210729091602_1](https://user-images.githubusercontent.com/25150787/127451440-e111b117-7fe4-4827-ac58-d6e71c72e4f5.jpg)
![20210729091602_2](https://user-images.githubusercontent.com/25150787/127451459-bfff4b5a-f651-4afd-8718-5d187139b7eb.jpg)

**R;B3**
![20210729094759_2](https://user-images.githubusercontent.com/25150787/127452808-732e3852-334c-4dc7-9bc1-6b735d7a7ca3.jpg)
![20210729094759_3](https://user-images.githubusercontent.com/25150787/127452821-bb68cd6d-5446-4249-9f87-d39ffcd53e61.jpg)

I also add my sepcs in case it would be of any help:
- Screen: 2560x1440 / 144hz
- OS: Windows 10 Pro 21H1
- CPU: AMD Ryzen 9 5900X 12-Core Processor 3.70 GHz
- RAM: 32GB DDR4 3200MHz
- GPU: NVIDIA GTX 1070ti 8GB GDDR5

**Comment by tlaik** [comment]
Try to set **Enable new FXAA and bloom** in the nep.ini to **No**, it should solve the black screen problem for now, though at the cost of a more blurred picture.
If it works, please also set "Log level" to 4 and run the game until main menu shows up, then quit and upload the nep.log somewhere. If you're still going to play after that, set log level back to 3 to keep your log file small.

**Comment by tlaik** [comment]
Try to set **Enable new FXAA and bloom** in the nep.ini to **No**, it should solve the black screen problem for now, though at the cost of a more blurred picture.
If it works, please also set "Log level" to 4 and run the game until main menu shows up, then quit and upload the nep.log somewhere. If you're still going to play after that, set log level back to 3 to keep your log file small.

**Comment by Oscarg73** [comment]
> Try to set **Enable new FXAA and bloom** in the nep.ini to **No**, it should solve the black screen problem for now, though at the cost of a more blurred picture.
> If it works, please also set "Log level" to 4 and run the game until main menu shows up, then quit and upload the nep.log somewhere. If you're still going to play after that, set log level back to 3 to keep your log file small.

Hi! I changed that setting to "No" and now the game looks blurrier as you said.
![image](https://user-images.githubusercontent.com/25150787/127465822-d2d39146-84af-4384-86f0-da98b74f2f33.png)
![20210729111407_1](https://user-images.githubusercontent.com/25150787/127465841-6123039a-aff4-47d2-94d6-38c502d0efbe.jpg)

But I keep getting the same plain black graphics. :(
![20210729111345_1](https://user-images.githubusercontent.com/25150787/127465921-58fbd32b-163e-460a-bcdb-7a689bc62df0.jpg)
![20210729111345_2](https://user-images.githubusercontent.com/25150787/127465940-36b6d79c-8ec1-47cd-8d92-f4bd82d94bd2.jpg)

**Comment by tlaik** [comment]
Alright, that's quite strange. Can you do the level 4 logging, the way I described, and send it to me? Also, please upload your nep.ini file. You can share both using https://pastebin.com

**Comment by Oscarg73** [comment]
> Alright, that's quite strange. Can you do the level 4 logging, the way I described, and send it to me? Also, please upload your nep.ini file. You can share both using https://pastebin.com

Hi! I uploaded them on WeTransfer because "nep.log" was too large for Pastebin. I hope there is no problem.

https://we.tl/t-T0MSmoBKOA

**Comment by tlaik** [comment]
Thanks, seems like not enough testing's been done with various game window sizes, and some screenspace effects wouldn't work outside 1920x1080. Try this out:
https://github.com/tlaik/neptastic/releases/tag/v1.1.4-bug/5.1

Also, you can turn on the new bloom/FXAA again.

**Comment by Oscarg73** [comment]
> Thanks, seems like not enough testing's been done with various game window sizes, and some screenspace effects wouldn't work outside 1920x1080. Try this out:
> https://github.com/tlaik/neptastic/releases/tag/v1.1.4-bug/5.1
> 
> Also, you can turn on the new bloom/FXAA again.

Hi, no problems now with that fix! Many thanks!
![20210729133113_1](https://user-images.githubusercontent.com/25150787/127484888-850b141b-3ef6-49d5-812c-1070049ade46.jpg)
![20210729133114_1](https://user-images.githubusercontent.com/25150787/127484902-bc71235a-c9fa-494e-bdca-0a246c397e83.jpg)
![20210729133117_1](https://user-images.githubusercontent.com/25150787/127484913-848e7c9a-02ce-4f06-be1e-693b1f678dca.jpg)
