### ISSUE TITLE
Incompatible with GOG ReBirth 3

### ISSUE THREAD

**Issue by Worgit** [tlaik/neptastic#7]
Hi, the GOG executable is called "NeptuniaReBirth3_NS.exe", which neptastic isn't picking up.  Also as a heads up, the GOG version doesn't have a ";" in the install directory, so dropping the files in the regular directory works for that version.

**Comment by tlaik** [comment]
Should be an easy fix, but do you know if previous games also have different exe names?

**Comment by Worgit** [comment]
I don't remember if 1 did, but it did work with neptastic.  2 has two different exe files.  The default is still "NeptuniaReBirth2.exe" and neptastic worked with that, but there's also another executable called "NeptuniaReBirth2_NS.exe".

**Comment by tlaik** [comment]
Sorry for the delay. Here's the new version, try it out:
https://github.com/tlaik/neptastic/releases/tag/v1.1.6

**Comment by Worgit** [comment]
Hi, I tried it with the GoG versions of all 3 games.  It still works for 1, but that never had any issues.  That only has one exe, and it's named the same as the steam version.  It also still works for the regular exe for 2.  Turns out that the second exe for 2 is actually called "NeptuniaReBirth2_do_NS.exe".  It crashes on startup even without neptastic, so I wouldn't be able to verify if a fix would work, or if the exe works at all.  3 is working now.

**Comment by tlaik** [comment]
Well, if that other RB2 exe crashes in any case, I doubt people will be using it.  Do you have any idea why it's there? Perhaps some debug version?

**Comment by Worgit** [comment]
My best guess is that might be some kind of debug or in-progess exe specifically for the GoG version that they forgot to remove.

**Comment by tlaik** [comment]
Alright, thanks for the feedback. I'll close the issue now.
