### ISSUE TITLE
[R3] Is possible use with Reshade?

### ISSUE THREAD

**Issue by marcussacana** [tlaik/neptastic#8]
I want use the Reshade SBS Stereo 3D feature...

**Comment by tlaik** [comment]
I've no idea since I never used Reshade and haven't even taken a deep look into what exactly it does to various games. If you have any experience with it, you're better off trying it yourself and seeing how it goes.

**Comment by mer2329** [comment]
ive used reshade through the Speacial k SKIF, didnt set it up though as i was trying to solve somthing.
